#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>

// function prototypes
char **generateGrayCode(int );   // Function to generate Gray codes of n bits, returns a dynamically allocated matrix of codes
void printGrayCodeMatrix(char **, int); // Function to print the matrix of Gray codes
void freeMatrix(char **, int); // Function to free dynamically allocated memory of the Gray code matrix

int main() {
    int n;  // Variable to store the number of bits input by the user
    printf("Enter the number of bits (n): ");
    scanf("%d", &n);  // Reads and stores the number of bits

    char **grayCodes = generateGrayCode(n); // Generate Gray codes of n bits and store in a dynamically allocated matrix
    printGrayCodeMatrix(grayCodes, n);      // Print the resulting matrix of Gray codes

    freeMatrix(grayCodes, (int)pow(2, n));  // Free allocated memory for the matrix to avoid memory leaks
    return 0;
}

// Generates Gray codes for n bits recursively
// Allocates space for 2^n Gray codes, each of length n
// Recursively builds codes by reflecting the previous list, then adding a 0 prefix to the original list and a 1 prefix to the reflected list
// Returns a matrix where each row is a Gray code in string form
char **generateGrayCode(int n) {
    int rows = (int)pow(2, n);           // Calculate tot_rows as 2^n (total number of Gray codes)
    char **grayCodes = malloc(rows * sizeof(char *)); // Allocate an array of pointers to hold each Gray code string

    for (int i = 0; i < rows; i++) {     // Loop to allocate memory for each code of length n + 1 (for null terminator)
        grayCodes[i] = malloc((n + 1) * sizeof(char)); // Each string has n bits + 1 space for null terminator
    }

    // Base case for n=1, starting the Gray code sequence
    if (n == 1) {
        strcpy(grayCodes[0], "0");   // Assign "0" to the first row
        strcpy(grayCodes[1], "1");   // Assign "1" to the second row
        return grayCodes;       // Return the base case matrix for n = 1
    }
    // Recursive call to get Gray codes for (n-1) bits, one less bit
    char **prevGrayCodes = generateGrayCode(n - 1);

    int half = rows / 2; // Midpoint of the list, dividing the list for reflection and prefixing
    // Prefix "0" to original list and "1" to reflected list
    for (int i = 0; i < half; i++) {
        snprintf(grayCodes[i], n + 1, "0%s", prevGrayCodes[i]); // Add "0" prefix to each code in original order
        snprintf(grayCodes[rows - i - 1], n + 1, "1%s", prevGrayCodes[i]); // Add "1" prefix to reflected codes (reverse order)
    }

    // Free memory of previous Gray codes generated by recursion (avoid memory leaks)
    freeMatrix(prevGrayCodes, half);
    return grayCodes;  // Return the filled Gray code matrix of n bits
}


// prints the matrix of Gray codes, each row contains one Gray code of n bits
void printGrayCodeMatrix(char **grayCodes, int n) {
    int rows = (int)pow(2, n);  // Calculate the total number of Gray codes as 2^n
    printf("Gray codes for %d bits:\n", n);

    for (int i = 0; i < rows; i++) {  // Loop through each row of the matrix to print each Gray code
        printf("%s\n", grayCodes[i]);    // Print each Gray code row as a string
    }
}

// frees dynamically allocated memory
void freeMatrix(char **matrix, int rows) {
    for (int i = 0; i < rows; i++) {   // Loop to free each row pointer in the matrix
        free(matrix[i]);  // Free allocated memory for each code (string)
    }
    free(matrix); // Finally, free the matrix pointer itself
}